### ISSUE TITLE
Body parsed regardless of Seneca-web options

### ISSUE THREAD

**Issue by paulnebel** [senecajs/seneca-web-adapter-koa1#11]
Seneca-web has an option 'parseBody' which, when set to false, should stop the adapter from parsing the request body (presumably because it has already been parsed). The express adapter correctly enforces this option (line 45).  The koa adapter does not.  This is a problem, as I need to set the limits for body parsing higher than the default for co-body and there's no way for me to do this if the seneca adapter insists on overriding my request not to parse the body.

Please update the koa adapter to respect the body parsing option in seneca-web.

Thanks

**Comment by tswaters** [comment]
That's a good call...  I even added that option to seneca-web and the express adapter, not sure how I missed it in this one.

I'll work on this.likely after I finish work, tonight ~10 hours or so.  Unless you want to send a PR prior to that.

I think this is an issue with koa2 adapter as well...

**Comment by tswaters** [comment]
This is done, available in v1.0.4
