### ISSUE TITLE
Body parsing inconsistent with REST and Seneca options

### ISSUE THREAD

**Issue by paulnebel** [senecajs/seneca-web-adapter-koa1#6]
Is there any particular reason why both this and the Koa2 adapter ignore the parseBody option and only parse the body on POST requests and not on PUT requests?

**Comment by tswaters** [comment]
Nope, that's a bug.

**Comment by tswaters** [comment]
PR is welcome, if you feel so inclined.

I'll probably get to it this coming weekend otherwise.

**Comment by tswaters** [comment]
This is now in v1.0.2
